### ISSUE TITLE
help shotgun trigger not work on controller

### ISSUE THREAD

**Issue by pppaluarit** [Jotalz/apex_dma_kvm_pub#28]
is there a way to make shotgun trigger work on controller?

**Comment by Jotalz** [comment]
Since this feature is pretty useless and I can't think of a way to improve it, so I almost don't use it.
If you want to try it, make the following changes and recompile: `apex_dma.cpp L453`
Effective when open scope.
`if (g_settings.shotgun_auto_shot && triggerbot_shotgun && isPressed(109)) {` 
to
 `if (g_settings.shotgun_auto_shot && triggerbot_shotgun && (zoom_state > 0)) {`
